{% set name = "seqpro" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ML4GLand/{{name}}/archive/refs/tags/v{{version}}.tar.gz

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip >=19.0.3
    - poetry-core >=1.0.0
    - python >=3.7,<3.11
  run:
    - python >=3.8,<3.11
    - numpy >=1.20.0
    - numba >=0.57.0
    - cyushuffle >=1.1.2

about:
  home: https://github.com/cast-genomics/haptools
  summary: Ancestry and haplotype aware simulation of genotypes and phenotypes for complex trait analysis
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aklie