[workspace]
authors = ["d-laub <dlaub@ucsd.edu>"]
channels = ["conda-forge", "bioconda"]
name = "SeqPro"
platforms = ["linux-64", "osx-arm64"]

[target.osx-arm64.activation.env]
LD_LIBRARY_PATH = "$CONDA_PREFIX/lib"
DYLD_LIBRARY_PATH = "$CONDA_PREFIX/lib"

[environments]
dev = { features = ["dev", "py310"] }
doc = { features = ["doc", "py312"] }
py310 = { features = ["py310"] }
py311 = { features = ["py311"] }
py312 = { features = ["py312"] }
py313 = { features = ["py313"] }
bench = { features = ["bench", "py313"] }

[tasks]
test = "pytest tests"
lint = "prek run --all-files --stage pre-commit"
prek-install = "prek install -t commit-msg -t pre-commit -t pre-push"
generate-publish = "maturin generate-ci -o .github/workflows/publish.yaml github"
typecheck = "pyrefly check python"

[dependencies]
python = "<3.14"
uv = "*"
maturin = "*"
pytest = "*"
pytest-cases = "*"
biopython = "*"
hypothesis = "*"
prek = "*"
ipykernel = ">=7.2.0,<8"
basedpyright = ">=1.39.3,<2"
seaborn = ">=0.13.2,<0.14"
statsmodels = ">=0.14.6,<0.15"
pyrefly = ">=1.0.0,<2"

[pypi-dependencies]
seqpro = { path = ".", editable = true }

[feature.dev.dependencies]
numba = "==0.58.1"
numpy = "==1.26.0"
polars = "==1.21.0"
pandera = "==0.31.1"
awkward = "==2.5.0"
narwhals = "==2.20.0"

[feature.dev.pypi-dependencies]
pyranges = "==0.1.3"

[feature.dev.tasks]
prek = "prek install --hook-type commit-msg"
i-kernel = "ipython kernel install --user --name seqpro"
bump-dry = "cz bump --dry-run"

[feature.doc.pypi-dependencies]
zensical = "*"
mkdocstrings-python = "*"

[feature.doc.tasks]
doc = "zensical serve"
build-doc = "zensical build --clean"

[feature.py310.dependencies]
python = "3.10.*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"

[feature.bench.pypi-dependencies]
tangermeme = "*"
dinuc-shuf = "*"
ipykernel = "*"
ipywidgets = "*"

[feature.bench.tasks]
i-kernel = "ipython kernel install --user --name seqpro-bench"

[feature.bench.dependencies]
marimo = ">=0.23.5,<0.24"
seaborn = ">=0.13.2,<0.14"
statsmodels = ">=0.14.6,<0.15"
