[workspace]
authors = ["d-laub <dlaub@ucsd.edu>"]
channels = ["conda-forge", "bioconda"]
name = "SeqPro"
platforms = ["linux-64"]

[environments]
dev = { features = ["dev", "py39"] }
doc = { features = ["doc", "py312"] }
py39 = { features = ["py39"] }
py310 = { features = ["py310"] }
py311 = { features = ["py311"] }
py312 = { features = ["py312"] }
py313 = { features = ["py313"] }

[dependencies]
numba = "*"
numpy = "*"
polars = "*"
pandera = "*"
pandas = "*"
natsort = "*"
pyarrow = "*"
awkward = "*"
uv = "*"
maturin = "*"
pytest = "*"
pytest-cases = "*"
biopython = "*"
hypothesis = "*"

[pypi-dependencies]
pyranges = "*"

[tasks]
install = "uv pip install -e ."
test = { cmd = "pytest tests", depends-on = ["install"] }

[feature.dev.dependencies]
numba = "==0.58.1"
numpy = "==1.26.0"
polars = "==1.10.0"
pandera = "==0.22.1"
pandas = "*"
natsort = "*"
pyarrow = "*"
awkward = "==2.5.0"
ipykernel = "*"

[feature.dev.pypi-dependencies]
pyranges = "==0.1.3"

[feature.dev.tasks]
pre-commit = "pre-commit install --hook-type commit-msg"
i-kernel = "ipython kernel install --user --name seqpro"
bump-dry = "cz bump --dry-run"
publish = """
    git checkout main && cz bump && git push --follow-tags && maturin publish
    && git checkout stable && git pull origin stable && git rebase main && git push origin stable
    && git checkout main
    """

[feature.doc.dependencies]
sphinx = "*"
sphinx-book-theme = "*"
sphinx-autobuild = "*"
sphinx-autodoc-typehints = "*"
myst-parser = "*"

[feature.doc.tasks]
doc = { cmd = "make clean && make html", cwd = "docs" }

[feature.py39.dependencies]
python = "3.9.*"

[feature.py310.dependencies]
python = "3.10.*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py313.dependencies]
python = "3.13.*"
