[tool.poetry]
name = "seqpro"
version = "0.0.1"
description = "Sequence preprocessing toolkit"
authors = ["adamklie <aklie@ucsd.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21.5"
torch = "^1.11.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
